development:
  dialect: "mysql"
  database: "apiwars_development"
  host: "localhost"
  port: "3306"
  user: "root"
  password: "root"

test:
  url: {{envOr "TEST_DATABASE_URL" "mysql://root@/apiwars_test?parseTime=true&multiStatements=true&readTimeout=1s"}}

production:
  url: {{envOr "DATABASE_URL" "mysql://root@/apiwars_production?parseTime=true&multiStatements=true&readTimeout=1s"}}
